# Generated by Django 4.1.2 on 2022-10-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='disk',
            new_name='disc',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='disk_type',
            new_name='disc_type',
        ),
    ]
