# Generated by Django 4.1.2 on 2022-10-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_remove_laptop_disk_boyutu_remove_laptop_disk_turu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='site',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='site_link',
        ),
    ]
