# Generated by Django 4.1.2 on 2022-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_remove_laptop_site_remove_laptop_site_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
